### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by cronchy** [madebyzuoa/ooze#1]
So, I don't know if I'm just stupid or if there's an issue with the installation. I downloaded/installed Python 3.8.6 and followed the steps you provided, but it is responding with this: 

"'pip3' is not recognized as an internal or external command,
operable program or batch file."

**Comment by madebyzuoa** [comment]
You need to reinstall and check the "Add to PATH" checkbox on the first screen of the installer.

**Comment by cronchy** [comment]
> You need to reinstall and check the "Add to PATH" checkbox on the first screen of the installer.

I did that and retried the first step in your installation process and now it says this:

" ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' "

When I try to do the command "python3 ooze.py", it tells me this:

" Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases. "

**Comment by madebyzuoa** [comment]
Not sure about the python error you're getting but you're probably getting the pip error because you're not cd'd into the directory of where you extracted the selfbot. Google your errors.
